# Generated by Django 3.2.16 on 2023-05-17 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='waterpredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.DecimalField(decimal_places=7, max_digits=15)),
                ('humidity', models.IntegerField()),
                ('soilMoisture', models.IntegerField()),
                ('waterLevel', models.IntegerField()),
                ('lighting', models.DecimalField(decimal_places=7, max_digits=15)),
                ('crop_type', models.CharField(choices=[('Pepper', 'Pepper'), ('Strawberry', 'Strawberry'), ('Lettuce', 'Lettuce'), ('Tomatoes', 'Tomatoes')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'WaterPredictions',
            },
        ),
        migrations.CreateModel(
            name='croppredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.DecimalField(decimal_places=7, max_digits=15)),
                ('P', models.DecimalField(decimal_places=7, max_digits=15)),
                ('K', models.DecimalField(decimal_places=7, max_digits=15)),
                ('temperature', models.DecimalField(decimal_places=7, max_digits=15)),
                ('humidity', models.DecimalField(decimal_places=7, max_digits=15)),
                ('ph', models.DecimalField(decimal_places=7, max_digits=15)),
                ('rainfall', models.DecimalField(decimal_places=7, max_digits=15)),
                ('perviouspredictions', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCropPredictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CropPredictions',
            },
        ),
    ]
