# Generated by Django 3.2.16 on 2023-02-01 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.DecimalField(decimal_places=7, max_digits=15)),
                ('P', models.DecimalField(decimal_places=7, max_digits=15)),
                ('K', models.DecimalField(decimal_places=7, max_digits=15)),
                ('temperature', models.DecimalField(decimal_places=7, max_digits=15)),
                ('humidity', models.DecimalField(decimal_places=7, max_digits=15)),
                ('ph', models.DecimalField(decimal_places=7, max_digits=15)),
                ('perviouspredictions', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserPredictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
