# Generated by Django 3.2.16 on 2023-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppredictions',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='croppredictions',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waterpredictions',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waterpredictions',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
