# Generated by Django 3.2.16 on 2023-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230616_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpredictions',
            name='actual',
            field=models.IntegerField(default=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterpredictions',
            name='water_loss',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
