# Generated by Django 3.2.16 on 2023-02-23 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_alter_predictions_perviouspredictions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictions',
            options={'verbose_name_plural': 'CropPredictions'},
        ),
        migrations.AlterField(
            model_name='predictions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCropPredictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='waterpredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.DecimalField(decimal_places=7, max_digits=15)),
                ('humidity', models.IntegerField()),
                ('soilMoisture', models.IntegerField()),
                ('waterLevel', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserWaterPredictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WaterPredictions',
            },
        ),
    ]
