# Generated by Django 3.2.16 on 2023-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20230616_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterpredictions',
            name='crop_type',
            field=models.CharField(choices=[('Pepper', 'Pepper'), ('Strawberry', 'Strawberry'), ('Tomatoes', 'Tomatoes')], max_length=100),
        ),
    ]
