# Generated by Django 3.2.16 on 2023-06-22 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_alter_waterpredictions_crop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpredictions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserwaterPredictions', to=settings.AUTH_USER_MODEL),
        ),
    ]
