# Generated by Django 3.2.16 on 2023-02-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_predictions_croppredictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croppredictions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waterpredictions',
            name='user',
        ),
    ]
