# Generated by Django 3.2.16 on 2023-02-23 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_auto_20230223_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppredictions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCropPredictions', to=settings.AUTH_USER_MODEL),
        ),
    ]
